Feature/zabbix
akamai-compute-marketplace/marketplace-apps pull request #124
Opened 2024-04-12 18:25 UTC by tbaka

Adds Ansible rewrite of Zabbix script.

2024-04-12 18:56 UTC, hmorris3293 commented on apps/linode-marketplace-zabbix/roles/zabbix/tasks/main.yml
We need to figure out how to get around the setup after login. Once deployed it brings you to the url, user has to  finish the install where it asks database info. Appears that the conf gets updated /etc/zabbix/web/zabbix.conf.php so we may be able to prefil that file to get around setup page

2024-04-15 16:14 UTC, n0vabyte requested changes

2024-04-15 16:14 UTC, n0vabyte commented on apps/linode-marketplace-zabbix/provision.yml
> +          zabbix_db_pass: {{ zabbix_db_pass }}
```suggestion
    - name: writing zabbix database password to vars
      lineinfile:
        insertafter: EOF
        path: group_vars/linode/vars
        line: | 
          zabbix_db_pass: {{ lookup('password', '/dev/null length=45 chars=ascii_letters,digits') }}
```

2024-04-15 16:14 UTC, n0vabyte commented on apps/linode-marketplace-zabbix/provision.yml
> +          zabbix_db_pass: {{ zabbix_db_pass }}
we don't have to set_fact to just write the creds to the vars file. We can just write directly.

2024-04-15 16:16 UTC, tbaka commented on apps/linode-marketplace-zabbix/roles/zabbix/tasks/main.yml
updated and added generated Admin pass

2024-04-16 14:49 UTC, n0vabyte requested changes

2024-04-16 14:49 UTC, n0vabyte commented on apps/linode-marketplace-zabbix/roles/zabbix/tasks/main.yml
> +    login: zabbix
```suggestion
```

2024-04-16 14:49 UTC, n0vabyte commented on apps/linode-marketplace-zabbix/roles/zabbix/tasks/main.yml
> +    login: zabbix
Playbook fails because of this param.

2024-04-16 15:31 UTC, n0vabyte requested changes
We don't have to proxy_pass to 8080 because this is already running the application. We should add a task to rename `/etc/nginx/conf.d/zabbix.conf{,.dis}`. Other than that, this is solid!

2024-04-16 15:31 UTC, n0vabyte commented on apps/linode-marketplace-zabbix/roles/zabbix/templates/vhost_ssl.conf.j2
> +        proxy_pass http://127.0.0.1:8080;
```suggestion
        #proxy_pass http://127.0.0.1:8080;
```

2024-04-16 15:31 UTC, n0vabyte commented on apps/linode-marketplace-zabbix/roles/zabbix/templates/vhost_ssl.conf.j2
> +    proxy_pass http://127.0.0.1:8080;
```suggestion
    #proxy_pass http://127.0.0.1:8080;
```

2024-04-16 16:37 UTC, n0vabyte approved these changes
Deployment passed after requested changes. :+1:

2024-04-16 16:38 UTC, merged