add SimpleX Chat
akamai-compute-marketplace/marketplace-apps pull request #30
Opened 2023-09-14 16:18 UTC by epoberezkin

2023-09-19 14:34 UTC, tbaka commented
howdy, I wanted to let you know that we're starting the review process for your submission. We have a thirty day window for new submissions to release _after_ they are passing tests. This would put you on October 16th.

2023-09-20 15:03 UTC, tbaka requested changes
This passes deploy, and we can merge to develop when requested changes are made

2023-09-20 15:03 UTC, tbaka commented on apps/linode-marketplace-simplex/logo.svg
The logo svgs need a full name attached. will you rename this to `/apps/linode-marketplace-simplex/assets/simplexchat.svg`

2023-09-20 15:03 UTC, tbaka commented on apps/linode-marketplace-simplex/requirements.txt
after EOF please add the following block. 
`### testing reqs ###
#molecule==5.1.0
#molecule-vagrant==2.0.0
#python-vagrant==0.5.15`

2023-09-26 18:04 UTC, epoberezkin commented
hello! cc @shumvgolove

2023-09-27 10:16 UTC, shumvgolove commented on apps/linode-marketplace-simplex/logo.svg
Done!

2023-09-27 10:16 UTC, shumvgolove commented on apps/linode-marketplace-simplex/requirements.txt
Done!

2023-09-27 10:18 UTC, shumvgolove commented
👋 @tbaka Could you take a look?

2023-09-28 14:14 UTC, tbaka approved these changes
Looks good!

2023-09-28 14:15 UTC, merged

2023-09-28 14:47 UTC, tbaka commented
We have your app scheduled for release on October 16th. Let me know if you have any questions.

2023-09-28 14:56 UTC, epoberezkin commented
@tbaka thank you!